### ISSUE TITLE
Handling of Dictionary and Wortersatzstrich

### ISSUE THREAD

**Issue by egli** [sbsdev/daisyproducer#14]
See http://redmine.sbszh.ch/issues/1777

- [x] change word recognition in Python
  - recognize words with Wortersatzstrich
- [x] add some code to [views.py](https://github.com/sbsdev/daisyproducer/blob/master/daisyproducer/dictionary/views.py#L114) to enhance the content with the standard box drawing character for Kürzungsverbot
- [x] and later do not drop the box drawing signs
- [x] add word to dictionary with the same dummy char that the correct uses

**Comment by mixa72** [comment]
Für die Umsetzung dieses Issues muss sämtlicher Code von "Korrektur der Bindestrich-Probleme" in sbs-de-core.mod mit folgendem ersetzt werden:

´´´´
# --- Korrektur der Bindestrich-Probleme ---------------------------------------

# Bindestrich nach Leerschlag vor Zahl ist Minuszeichen.
noback correct $s["-"]$d "\x2212"
# Bindestrich nach öffnender Klammer vor Zahl ist Minuszeichen.
noback correct ["(-"]$d "(\x2212"
noback correct ["[-"]$d "[\x2212"
# begword nach Wortersatzstrich verhindern
noback correct $s["-"] "-\x250A"
# begword nach Satzzeichen und Wortersatzstrich verhindern
noback correct $s["(-"] "(\x2013\x250A"
noback correct $s["»-"] "»\x2013\x250A"
noback correct $s["›-"] "›\x2013\x250A"
# begword nach Wortersatzstrich nach Schrägstrich verhindern
noback correct ["/-"]$l "/\x2013\x250A"
# endword vor Wortersatzstrich vor Schrägstrich verhindern
noback correct $l["-/"] "\x250A-/"
# endword vor Wortersatzstrich verhindern
noback correct "-\s" "\x250A-\s"
# endword vor Wortersatzstrich und Satzzeichen verhindern
noback correct "-.\s" "\x250A-.\s"
noback correct "-,\s" "\x250A-,\s"
noback correct "-;\s" "\x250A-;\s"
noback correct "-:\s" "\x250A-:\s"
noback correct "-!\s" "\x250A-!\s"
noback correct "-?\s" "\x250A-?\s"
noback correct "-)\s" "\x250A-)\s"
noback correct "-«\s" "\x250A-«\s"
noback correct "-‹\s" "\x250A-‹\s"
# begword/endword vor/nach Auslassungspunkten verhindern
noback correct $l["..."]$l "\x250A...\x250A"
noback correct $l["..."] "\x250A..."
noback correct ["..."]$l "...\x250A"
´´´´
