### ISSUE TITLE
Fehler beim Sammeln unbekannter Wörter (Wortkompositionen im Dictionary, die nicht im Text vorhanden sind)

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer#22]
xml enthält:
````
blabli-blabli- blable-blable-
````
und mehrfach das Wort "bla" im Text

Unter "Unbekannte Wörter" erscheinen:
````
blabli┊
blable┊
blablibli  <- falscher Eintrag
blableble  <- falscher Eintrag
````
Siehe Test-Datei:
[blable.txt](https://github.com/sbsdev/daisyproducer/files/3610535/blable.txt)

**Comment by egli** [comment]
Fixed in d8545ebe26d7dd02001f25738cfb9d99a60f85d8
