### ISSUE TITLE
Fehler beim Sammeln unbekannter Wörter (Zahl-Wort-Kompositionen)

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer#23]
xml enthält:
````
10-Uhr-Pause
````

Unter "Unbekannte Wörter" erscheint:
````
┊uhr     <- falscher Eintrag
````
  
Es handelt sich nicht um einen Wortersatzstrich, sondern Bindestrich. Dieser darf nicht im Dictionary erscheinen.

**Comment by egli** [comment]
Fixed in 1aeeeb350bfb07480a5e19c0113d6a10fa9799a3
