### ISSUE TITLE
Fehler beim Erfassen von Wörtern mit Wortersatzstrichen bei Zusammensetzungen mit Tags wie abbr, brl:num

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer#24]
Eingabe:
````
Bauchspeicheldrüsenkrebs-<abbr>OP</abbr>
<abbr>US</abbr>-Exekutionskommandogrenadier
<brl:num role="measure">22 mm</brl:num>-Kaliberfabrikant
````

Dictionary:
````
bauchspeicheldrüsenkrebs┊
┊exekutionskommandogrenadier
┊kaliberfabrikant
````

Problem: Tags wie abbr, brl:num, brl:select etc. werden vor dem Texttransfer in den Dictionary herausgefiltert. Somit bleiben im Text Wörter mit Bindestrichen zurück (bauchspeicheldrüsenkrebs-, -exekutionskommandogrenadier, -kaliberfabrikant). Diese werden dann fälschlicherweise von der Regexp als Wortersatzstriche interpretiert und gelangen so in den Dictionary (haben aber gar keinen Wortersatzstrich und sind dort somit auch nicht korrigierbar).

**Comment by mixa72** [comment]
Gute Lösung so! Jetzt noch die beiden folgenden Fälle abdecken:
````
  <brl:name>McEnroe</brl:name>-Rückhand
  <brl:computer>www.ubs.com</brl:computer>-Webseite
````
siehe https://github.com/sbsdev/daisyproducer/blob/master/daisyproducer/dictionary/xslt/filter.xsl
Danke

**Comment by egli** [comment]
Fixed in 06d68d42e2495e3da68e05a521e8347dc3cfe39b, a79025ec6c927af993c823a0c999246078bcb110 and a31a8d6deccad0a71674c67fb071ece3ffdaada1

**Comment by mixa72** [comment]
Ein erstes Feedback der User hat gezeigt, dass Elemente wie abbr, brl:num, brl:name und brl:computer auch oft links und rechts Bindestriche aufweisen. Dies muss noch in https://github.com/sbsdev/daisyproducer/blob/master/daisyproducer/dictionary/xslt/filter.xsl für besipielsweise folgende Fälle ergänzt werden:
````
<p> Studenten-<abbr>WG</abbr>-Saustall </p>
<p> Kalaschnikow-<brl:num role="measure">7,62 mm</brl:num>-Kaliber </p>
<p> Post-<brl:name>McCartney</brl:name>-Ära </p>
<p> Zuckerberg-<brl:computer>facebook.com</brl:computer>-Skandal </p>
````
Besten Dank!

**Comment by mixa72** [comment]
Beim Markup in einzelne P's ist Resultat befriedigend:
````
<p> Studentenyyy-<abbr>WG</abbr>-Saustallyyy </p>
<p> Kalaschnikowyyy-<brl:num role="measure">7,62 mm</brl:num>-Kaliberyyy </p>
<p> Postyyy-<brl:name>McCartney</brl:name>-Ärayyy </p>
<p> Zuckerbergyyy-<brl:computer>facebook.com</brl:computer>-Skandalyyy </p>
````
Nicht aber, wenn alles in einem P:
````
<p>
 Studentenxxx-<abbr>WG</abbr>-Saustallxxx 
 Kalaschnikowxxx-<brl:num role="measure">7,62 mm</brl:num>-Kaliberxxx 
 Postxxx-<brl:name>McCartney</brl:name>-Äraxxx  
 Zuckerbergxxx-<brl:computer>facebook.com</brl:computer>-Skandalxxx 
</p>
````
Dann werden folgende Wörter misinterpretiert:
kalaschnikowxxx┊
zuckerbergxxx┊
┊kaliberxxx
