### ISSUE TITLE
Trennungen bei Wörtern mit ┊ verschwinden beim Übergang von "Unbekannte Wörter" zu "Lokale Wörter"

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer#26]
1) Datei mit ┊-Wort uploaden
http://xmlp02.sbszh.ch/todo/660/markup
wertendlichungsmaschinerie...

2) Wort erscheint im Dictionary unter "Unbekannte Wörter"
http://xmlp02.sbszh.ch/todo/660/check_words_g2
Schwarzschrift: wertendlichungsmaschinerie┊
Braille: W7TCD_USM570┊

3) Braille-Output mit Silbentrennung (Wort ist noch nicht in "Lokale Wörter")
Output (mit Trennungen): W7tTCDt_UStM570...

4) Wort im Dictionary abspeichern (Wort geht zu "Lokale Wörter", aber UNVERÄNDERT)
http://xmlp02.sbszh.ch/todo/660/local_words_g2
Schwarzschrift: wertendlichungsmaschinerie┊
Braille: W7TCD_USM570┊

5) Braille-Output mit Silbentrennung (Wort ist in "Lokale Wörter")
Output (OHNE Trennungen): W7TCD_USM570...

Normalerweise (bei Wörtern ohne ┊) führt nur eine Veränderung der Brailleübersetzung zum Ausbleiben der Trennungen, nicht aber ein einfaches Abspeichern des Status quo.

**Comment by egli** [comment]
The problem is that in `brailleTables.py` it translates the word "Wertendlichungsmaschinerie┊" and checks if the translation is the same as the given braille. Unfortunately due to `sbs-special.mod` the Kürzungsverbot, i.e. "┊" is removed from the Braille so the translation will never be correct and it will put the Braille in the local dictionary.

And that is the other thing, as soon as a word is defined in the local dictionary it will no longer be hyphenated.

We need to find a way that we can avoid the `pass2` (in `sbs-special.mod`) that cleans out all `DUMMY_TEXT`.

**Comment by egli** [comment]
There are two solutions to handle this problem
1. Remove the `DUMMY_TEXT` before comparing it to the liblouis translation.
2. do not even store the `DUMMY_TEXT` in the database. Then the comparison wouldn't fail. Also we wouldn't write the seemingly useless  `DUMMY_TEXT` (which is removed by a `pass2` anyway) in the white list tables.

## Why keep the `DUMMY_TEXT` in the database?

Why should the `DUMMY_TEXT` be in the database? It makes no sense to show it to the user, it complicates the comparison when writing the white list tables and it is cleaned out by a `pass2` anyway. So why keep it at all? According to @cwaldvogel there are several reasons to do so:

- For the user it gives an visual indication that there is something special about this translation
- When exporting the dictionary words the `DUMMY_TEXT` apparently helps to create better [hyphenation based translation rules](https://github.com/liblouis/liblouis/wiki/Hyphenation-based-translation)

## Conclusion

For above reasons we are going for solution 1, e.g. 
- [ ] keep the `DUMMY_TEXT` in the database 
- [ ] Remove the `DUMMY_TEXT` before comparing it to the liblouis translation.
- [ ] Drop the `DUMMY_TEXT` before writing the white list table
