### ISSUE TITLE
Fehler beim Sammeln unbekannter Wörter (Wörter im Dictionary, die nicht im Text vorhanden sind)

### ISSUE THREAD

**Issue by mixa72** [sbsdev/daisyproducer#34]
Text im XML:
````
<p> Magister-  er- </p>
````
Im Braille Dictionary erscheint:
````
er┊ 7┊
magist MAGI]              <-- Fehler
magister┊ MAGI]7┊
````
![screenshot_braille_dictionary](https://user-images.githubusercontent.com/1667959/89196249-3a731a80-d5aa-11ea-8e4d-ed695b66179a.png)

Siehe auch http://xmlp02.sbszh.ch/todo/699/check_words_g2

**Comment by egli** [comment]
@mixa72 is this still an issue with daisyproducer2?
